### ISSUE TITLE
Just want to say thanks

### ISSUE THREAD

**Issue by PThorpe92** [artempyanykh/Fang#1]
Hey man, 
After finding you on youtube and pretty much binge-watching literally all of your content, I wanted to say I am amazed that you don't have more subscribers... Just absolutely fantastic content, it's so hard to find good, high quality technical SWE content that isn't focused at beginner/intermediate level viewers. Obviously you are limiting your views by producing content with such advanced topics, but I would like to let you know that that are really appreciated! and I really hope you continue to make them.

- Preston

**Comment by artempyanykh** [comment]
Thanks for the kind words @PThorpe92, appreciate it! I do question from time to time why I spend my time on this, but knowing that people out there find the content valuable definitely helps me keep going.

**Comment by PThorpe92** [comment]
It was that exact thought that made me want to find this and post something lol

I'm gonna post your videos in a couple forums and maybe post the Ocaml raytracer on hackernews and see what happens :+1:
